spring:
    datasource:
#        url: jdbc:mysql://localhost:3306/board?useSSL=false&serverTimezone=Asia/Seoul
#        username: root
#        password: secret12
        url: jdbc:mysql://awseb-e-92ahyx9iy9-stack-awsebrdsdatabase-dqtonnrrcrbo.crz4ofrogemb.ap-northeast-2.rds.amazonaws.com/board?useSSL=false&serverTimezone=Asia/Seoul
        username: myboard
        password: rlaqhdgy12!
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
